/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.77
 * Generated at: 2017-05-11 04:14:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.sys.module;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!-- Main Header -->\n");
      out.write("<header class=\"main-header\">\n");
      out.write("\n");
      out.write("\t<!-- Logo -->\n");
      out.write("\t<a href=\"index2.html\" class=\"logo\"> <!-- mini logo for sidebar mini 50x50 pixels -->\n");
      out.write("\t\t<span class=\"logo-mini\"><b>快易收</b></span> <!-- logo for regular state and mobile devices -->\n");
      out.write("\t\t<span class=\"logo-lg\"><b>快易收</b>后台</span>\n");
      out.write("\t</a>\n");
      out.write("\n");
      out.write("\t<!-- Header Navbar -->\n");
      out.write("\t<nav class=\"navbar navbar-static-top\" role=\"navigation\">\n");
      out.write("\t\t<!-- Sidebar toggle button-->\n");
      out.write("\t\t<a href=\"javascript:;\" class=\"sidebar-toggle\" data-toggle=\"offcanvas\"\n");
      out.write("\t\t\trole=\"button\" style=\"font-size :14px;padding-bottom: 9px;\"> <span class=\"sr-only\">导航开关</span>\n");
      out.write("\t\t</a>\n");
      out.write("\t\t<!-- Navbar Right Menu -->\n");
      out.write("\t\t<div class=\"navbar-custom-menu\">\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav\">\n");
      out.write("\t\t\t\t<!-- User Account Menu -->\n");
      out.write("\t\t\t\t<li class=\"dropdown user user-menu\">\n");
      out.write("\t\t\t\t\t<!-- Menu Toggle Button --> <a href=\"javascript:;\" class=\"dropdown-toggle\"\n");
      out.write("\t\t\t\t\tdata-toggle=\"dropdown\"> <!-- The user image in the navbar--> <img\n");
      out.write("\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/static/AdminLTE/dist/img/user.jpg\" class=\"user-image\"\n");
      out.write("\t\t\t\t\t\talt=\"User Image\" /> <!-- hidden-xs hides the username on small devices so only the image appears. -->\n");
      out.write("\t\t\t\t\t\t<span class=\"hidden-xs\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span>\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\n");
      out.write("\t\t\t\t\t\t<!-- The user image in the menu -->\n");
      out.write("\t\t\t\t\t\t<li class=\"user-header\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/static/AdminLTE/dist/img/user.jpg\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"img-circle\" alt=\"User Image\" />\n");
      out.write("\t\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(" <small>上次登录");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.lastLogin}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</small>\n");
      out.write("\t\t\t\t\t\t\t</p></li>\n");
      out.write("\t\t\t\t\t\t<!-- Menu Footer-->\n");
      out.write("\t\t\t\t\t\t<li class=\"user-footer\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"pull-left\">\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"javascript:;\" data-url=\"user/editPwd\" data-model='dialog' class=\"btn btn-default btn-flat\">修改密码</a>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"pull-right\">\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"logout\" class=\"btn btn-default btn-flat\">退出</a>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t\t<!-- Control Sidebar Toggle Button -->\n");
      out.write("\t\t\t\t<li><a href=\"javascript:;\" data-toggle=\"control-sidebar\"><i\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-gears\"></i></a></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</div>\n");
      out.write("\t</nav>\n");
      out.write("</header>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
